name: Oxygen Documentation Action
description: Document your schemas using Oxygen Scripting
branding:
  icon: 'book-open'
  color: 'blue'
inputs:
  schemaFile:
    description: 'Schema file to generate documentation for.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout main repo.
      uses: actions/checkout@v3.3.0

    - name: Checkout Documentation Template repo.
      uses: actions/checkout@v3.3.0
      with:
        repository: oxygenxml/oxygen-script-documentation-template
        path: scripting

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Make gradlew executable
      run: chmod +x ./scripting/build/gradlew
      shell: bash

    - name: Build with Gradle
      run: cd scripting/build; ./gradlew generateDoc -PschemaFile=${{ inputs.schemaFile }} -PinnerBuild=false --info --stacktrace --build-cache
      shell: bash

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        folder: scripting/doc
